### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by mrocklin** [eriknw/dask-patternsearch#10]
It would be easier to show this to people if there were docstrings for the main user-facing functions (just search?) with good descriptions of the parameters.

**Comment by eriknw** [comment]
Agreed.  I plan to make this more presentable this weekend.

**Comment by eriknw** [comment]
Docstring added to `search`.  I also added a couple tests (which, naturally, required a couple fixes).  Once I add a basic README, this should be somewhat presentable.

Thanks for your interest, eagerness, and patience.
