### ISSUE TITLE
Submit more than ncores tasks

### ISSUE THREAD

**Issue by mrocklin** [eriknw/dask-patternsearch#2]
It might make sense to submit more tasks than there are workers.  This would help to cover up downtime while communicating results.  Workers like having a bit of a backlog to stay busy.

**Comment by eriknw** [comment]
I totally agree, and this should be discussed in the (non-existent) docs.  What do you recommend as the default w.r.t. ncores?

The user can manually specify this with the `queue_size=` argument, which doesn't need to relate to `ncores` at all.  Behaviorally, one may want to submit more (maybe many more) tasks than there are cores to "slow down" the algorithm and more exhaustively search the region, which may help if there are multiple minima.

**Comment by mrocklin** [comment]
From an occupancy perspective I'd recommend submitting the number of available cores +1 for every process.

```python
ncores = client.ncores()
total = sum(ncores.values()) + len(ncores)
```

**Comment by eriknw** [comment]
What, no PR?!  I like that default.  Thanks.
